intent: k8s_resource
flavor: k8s
version: '0.2'
description: Adds k8s_resource - k8s flavor
clouds:
- gcp
- kubernetes
- azure
- aws
sample:
  $schema: https://facets-cloud.github.io/facets-schemas/schemas/k8s_resource/k8s_resource.schema.json
  kind: k8s_resource
  metadata: {}
  flavor: k8s
  version: '0.2'
  disabled: true
  provided: false
  lifecycle: ENVIRONMENT
  advanced:
    k8s_resource:
      cleanup_on_fail: true
      timeout: 300
      wait: false
  spec:
    resource:
      apiVersion: v1
      kind: Service
      metadata:
        name: k8s-resource
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-scheme: internal
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
      spec:
        selector:
          app: facetsapi
        type: ClusterIP
        ports:
        - port: 80
          name: http
          targetPort: 80
