intent: pvc
flavor: k8s
version: '0.1'
description: Adds pvc - k8s flavor
clouds:
- aws
- gcp
- azure
- kubernetes
sample:
  $schema: https://facets-cloud.github.io/facets-schemas/schemas/pvc/pvc.schema.json
  flavor: k8s
  kind: pvc
  disabled: 'false'
  metadata:
    name: test-pvc
  spec:
    size:
      volume: 8Gi
  advanced:
    accessModes:
    - ReadWriteOnce
