intent: helm
flavor: k8s
version: '0.1'
description: Adds Helm module
clouds:
  - aws
  - azure
  - gcp
  - kubernetes
spec:
  title: Helm
  description: Specification of the Helm chart intent
  type: object
  properties:
    helm:
      title: Helm
      description: Configuration for the Helm chart
      type: object
      properties:
        chart:
          type: string
          title: Chart
          description: URL or local path to the Helm chart package
          x-ui-placeholder: Enter URL or local path
        repository:
          type: string
          title: Repository
          description: URL for the helm repository
          x-ui-placeholder: Enter repository URL
        version:
          type: string
          title: Version
          description: Version for the helm chart
          x-ui-placeholder: Enter the valid chart version
        namespace:
          type: string
          title: Namespace
          description: Namespace to deploy the Helm chart in
          x-ui-placeholder: Enter namespace
        wait:
          type: boolean
          title: Wait
          description: Whether to wait for the Helm chart deployment to complete
        repository_username:
          type: string
          title: Repository Username
          description: Username to authenticate to private helm repository
          x-ui-placeholder: Enter repository username
        repository_password:
          type: string
          title: Repository Password
          description: Password to authenticate to private helm repository
          x-ui-placeholder: Enter repository password
          x-ui-mask-content: true
      required: [ "chart" ]
    values:
      type: object
      title: Values
      description: The values to be passed on to the chart in the form of a YAML object
      x-ui-yaml-editor: true
      x-ui-placeholder: Enter values in YAML format
  required: [ "helm", "values" ]
sample:
  $schema: 'https://facets-cloud.github.io/facets-schemas/schemas/helm/helm.schema.json'
  kind: helm
  flavor: k8s
  disabled: true
  metadata: {}
  version: '0.1'
  spec:
    helm:
      repository: >-
        https://helm.datadoghq.com
      chart: datadog
      namespace: default
      wait: false
    values: