intent: kubernetes_secret
flavor: k8s
version: '0.1'
clouds:
  - aws
  - azure
  - gcp
  - kubernetes
spec:
  type: object
  title: Kubernetes secret
  description: Specification of the kubernetes secret resource intent
  properties:
    data:
      type: object
      title: Data
      description: Random data
      x-ui-key-value: true
      patternProperties:
        type: object
        title: Data Name
        description: data name
        keyPattern: '^[0-9]+[m]?$'
        properties:
          value:
            type: string
            title: Value
            description: Value of Data
            pattern: '^(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$'
            x-ui-placeholder: "Enter the port number to expose for your application container"
            x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 0-65535"
        required:
          - value
    additionalProperties: false

sample:
  $schema: >-
    https://facets-cloud.github.io/facets-schemas/schemas/kubernetes_secret/kubernetes_secret.schema.json
  kind: kubernetes_secret
  disabled: true
  flavor: k8s
  version: '0.1'
  metadata: {}
  spec:
    data:
      username: dXNlcm5hbWU=
      password: cGFzc3dvcmQ=