intent: kubernetes_secret
flavor: k8s
version: '0.1'
clouds:
  - aws
  - azure
  - gcp
  - kubernetes
spec:
  type: object
  properties:
    data:
      type: object
      title: Data
      description: Data in key, value pair for config-map to be added in string
      x-ui-key-value: true
      patternProperties:
        type: string
        x-ui-key-value: true
        title: Data Name
        description: data name
        properties:
          value:
            type: string
            title: Value
            description: Value of Data
            x-ui-placeholder: "Enter the value of the secret"
        required:
          - value
sample:
  $schema: >-
    https://facets-cloud.github.io/facets-schemas/schemas/kubernetes_secret/kubernetes_secret.schema.json
  kind: kubernetes_secret
  disabled: true
  flavor: k8s
  version: '0.1'
  metadata: {}
  spec:
    data:
      username: dXNlcm5hbWU=
      password: cGFzc3dvcmQ=