intent: kubernetes_secret
flavor: k8s
version: '0.1'
clouds:
  - aws
  - azure
  - gcp
  - kubernetes
spec:
  type: object
  properties:
    data:
      title: data
      type: object
      description: Enter the key value pair for secret in string format
      x-ui-yaml-editor: true
      x-ui-placeholder: Enter the value of the secret. Eg 'key':'secret_value'
sample:
  $schema: >-
    https://facets-cloud.github.io/facets-schemas/schemas/kubernetes_secret/kubernetes_secret.schema.json
  kind: kubernetes_secret
  disabled: true
  flavor: k8s
  version: '0.1'
  metadata: {}
  spec:
    data:
      username: dXNlcm5hbWU=
      password: cGFzc3dvcmQ=