intent: schemahero_table
flavor: k8s
version: '0.1'
description: Adds schemahero_table - k8s flavor
clouds:
- aws
- gcp
- azure
- kubernetes
sample:
  $schema: https://facets-cloud.github.io/facets-schemas/schemas/schemahero_table/schemahero_table.schema.json
  flavor: k8s
  kind: schemahero_table
  version: '0.1'
  disabled: true
  metadata: {}
  spec:
    database: schemahero
    connection: mysql
    primary_key:
    - code
    columns:
      '1':
        name: code
        type: char(4)
      '2':
        name: name
        type: varchar(100)
      '3':
        name: dummy2
        type: varchar(100)
