spec:
  title: K8s
  $schema: http://json-schema.org/draft-07/schema#
  type: object
  properties:
    postgres_version:
      type: string
      title: Postgres version
      description: Version of postgres e.g. 13.3
      minLength: 1
    size:
      type: object
      title: Size
      description: Writer reader datastore sizing
      properties:
        reader:
          type: object
          title: reader
          description: Reader
          properties:
            cpu:
              type: string
              title: CPU
              description: The number of CPU cores required
              minLength: 1
              pattern: "^[0-9]+[m]?$"
            memory:
              type: string
              title: Memory
              description: The amount of memory required
              minLength: 1
              pattern: "^[0-9]+(\\.[0-9]+)?[EiKMGTP]i?$"
            cpu_limit:
              type: string
              title: CPU limit
              description: The CPU limit to set a maximum limit on the amount of CPU resources utilization, e.g '1' or '1000m'
              minLength: 1
              pattern: "^[0-9]+[m]?$"
            memory_limit:
              type: string
              title: Memory limit
              description: The memory limit to set a maximum limit on the amount of memory resources utilization, e.g '800Mi' or '1.5Gi'
              minLength: 1
              pattern: "^[0-9]+(\\.[0-9]+)?[EiKMGTP]i?$"
            instance_count:
              type: integer
              title: Instance count
              description: The number of instances to create
              minimum: 1
          required:
            - instance_count
            - cpu
            - memory
        writer:
          type: object
          title: writer
          description: Writer
          properties:
            cpu:
              type: string
              title: CPU
              description: The number of CPU cores required
              minLength: 1
              pattern: "^[0-9]+[m]?$"
            memory:
              type: string
              title: Memory
              description: The amount of memory required
              minLength: 1
              pattern: "^[0-9]+(\\.[0-9]+)?[EiKMGTP]i?$"
            cpu_limit:
              type: string
              title: CPU limit
              description: The CPU limit to set a maximum limit on the amount of CPU resources utilization, e.g '1' or '1000m'
              minLength: 1
              pattern: "^[0-9]+[m]?$"
            memory_limit:
              type: string
              title: Memory limit
              description: The memory limit to set a maximum limit on the amount of memory resources utilization, e.g '800Mi' or '1.5Gi'
              minLength: 1
              pattern: "^[0-9]+(\\.[0-9]+)?[EiKMGTP]i?$"
          required:
            - cpu
            - memory
  required:
    - size
    - postgres_version
  order:
    - postgres_version
    - size
