spec:
  title: K8s
  type: object
  properties:
    postgres_version:
      type: string
      title: Postgres Version
      description: Version of postgres e.g. 13.3
      minLength: 1
    size:
      type: object
      title: Size
      description: Writer reader datastore sizing
      properties:
        reader:
          type: object
          title: Reader
          description: Reader
          properties:
            cpu:
              type: string
              title: CPU
              description: The number of CPU cores required
              minLength: 1
              pattern: "^[0-9]+[m]?$"
            memory:
              type: string
              title: Memory
              description: The amount of memory required
              minLength: 1
              pattern: "^[0-9]+(\\.[0-9]+)?[EiKMGTP]i?$"
            cpu_limit:
              type: string
              title: CPU Limit
              description: Set a maximum limit on the amount of utilization
              x-ui-placeholder: e.g '1' or '1000m'
              minLength: 1
              pattern: "^[0-9]+[m]?$"
            memory_limit:
              type: string
              title: Memory Limit
              description: Set a maximum limit on the amount of utilization
              x-ui-placeholder: e.g '800Mi' or '1.5Gi'
              minLength: 1
              pattern: "^[0-9]+(\\.[0-9]+)?[EiKMGTP]i?$"
            instance_count:
              type: integer
              title: Instance Count
              description: The number of instances to create
              minimum: 1
          required:
            - instance_count
            - cpu
            - memory
        writer:
          type: object
          title: Writer
          description: Writer
          properties:
            cpu:
              type: string
              title: CPU
              description: The number of CPU cores required
              minLength: 1
              pattern: "^[0-9]+[m]?$"
            memory:
              type: string
              title: Memory
              description: The amount of memory required
              minLength: 1
              pattern: "^[0-9]+(\\.[0-9]+)?[EiKMGTP]i?$"
            cpu_limit:
              type: string
              title: CPU Limit
              description: Set a maximum limit on the amount of utilization
              x-ui-placeholder: e.g '1' or '1000m'
              minLength: 1
              pattern: "^[0-9]+[m]?$"
            memory_limit:
              type: string
              title: Memory Limit
              description: Set a maximum limit on the amount of utilization
              x-ui-placeholder: e.g '800Mi' or '1.5Gi'
              minLength: 1
              pattern: "^[0-9]+(\\.[0-9]+)?[EiKMGTP]i?$"
          required:
            - cpu
            - memory
  required:
    - size
    - postgres_version
  x-ui-order:
    - postgres_version
    - size
sample:
  $schema: >-
    https://facets-cloud.github.io/facets-schemas/schemas/postgres/postgres.schema.json
  flavor: k8s
  metadata: { }
  kind: postgres
  disabled: true
  version: 0.1
  spec:
    postgres_version: 15.3.0
    size:
      writer:
        cpu: 1000m
        memory: 1000Mi
        cpu_limit: 1000m
        memory_limit: 1000Mi
      reader:
        cpu: 200m
        memory: 800Mi
        cpu_limit: 1000m
        memory_limit: 1000Mi
        instance_count: 1
