name: prometheus
description: Deploys Prometheus monitoring stack on Kubernetes
provider: kubernetes
type: monitoring
version: "0.1"

intent: monitoring
flavor: k8s

clouds:
  - aws
  - azure
  - gcp
  - kubernetes

inputs:
  kubernetes_details:
    optional: false
    type: "@output/kubernetes"
    default:
      resource_type: kubernetes_cluster
      resource_name: default

spec:
  title: Prometheus Stack
  type: object
  properties:
    values:
      type: object
      title: Custom Values
      description: Additional values to pass to the Prometheus helm chart
      default: {}

    retention:
      type: string
      title: Data Retention
      description: Time duration Prometheus shall retain data for
      default: "100d"
      pattern: "^[0-9]+(d|h|m)$"
      x-ui-placeholder: "e.g., 100d, 24h, 1440m"

    node_selector:
      type: object
      title: Node Selector
      description: Node selector configuration for Prometheus components
      patternProperties:
        "^[a-zA-Z0-9_.-]*$":
          type: object
          title: Node Selector Label
          description: Node selector label configuration
          properties:
            key:
              type: string
              title: Label Key
              description: Kubernetes node label key
            value:
              type: string
              title: Label Value
              description: Value for the node selector label
          required:
            - key
            - value

    tolerations:
      type: array
      title: Tolerations
      description: Pod tolerations for Prometheus components
      items:
        type: object
        properties:
          key:
            type: string
            title: Key
            description: The taint key to tolerate
          operator:
            type: string
            title: Operator
            description: Operator for the toleration
            enum:
              - Equal
              - Exists
          value:
            type: string
            title: Value
            description: Value for the toleration
          effect:
            type: string
            title: Effect
            description: The taint effect to tolerate
            enum:
              - NoSchedule
              - PreferNoSchedule
              - NoExecute

    operator:
      type: object
      title: Prometheus Operator
      properties:
        enabled:
          type: boolean
          title: Enable Operator
          description: Enable/disable Prometheus operator
          default: true
        enable_crds:
          type: boolean
          title: Install CRDs
          description: Enable/disable CRD installation
          default: true
        size:
          type: object
          title: Operator Size
          properties:
            resources:
              type: object
              properties:
                requests:
                  type: object
                  properties:
                    cpu:
                      type: string
                      pattern: "^([1-9]|[12][0-9]|3[0-2])$|^(3[0-1][0-9]{3}|[1-2][0-9]{4}|[1-9][0-9]{0,3}|32000)m$"
                      default: "200m"
                    memory:
                      type: string
                      pattern: "^([1-9]|[1-5][0-9]|6[0-4])Gi$|^([1-9]|[1-9][0-9]{1,3}|[1-5][0-9]{4}|6[0-3][0-9]{3}|64000)Mi$"
                      default: "512Mi"
                limits:
                  type: object
                  properties:
                    cpu:
                      type: string
                      pattern: "^([1-9]|[12][0-9]|3[0-2])$|^(3[0-1][0-9]{3}|[1-2][0-9]{4}|[1-9][0-9]{0,3}|32000)m$"
                      default: "200m"
                    memory:
                      type: string
                      pattern: "^([1-9]|[1-5][0-9]|6[0-4])Gi$|^([1-9]|[1-9][0-9]{1,3}|[1-5][0-9]{4}|6[0-3][0-9]{3}|64000)Mi$"
                      default: "512Mi"

    prometheus:
      type: object
      title: Prometheus Server
      properties:
        enabled:
          type: boolean
          title: Enable Prometheus
          description: Enable/disable Prometheus server
          default: true
        size:
          type: object
          title: Server Size
          properties:
            volume:
              type: string
              pattern: "^[0-9]+(\\.[0-9]+)?[G]i?$"
              default: "100Gi"
            resources:
              type: object
              properties:
                requests:
                  type: object
                  properties:
                    cpu:
                      type: string
                      pattern: "^([1-9]|[12][0-9]|3[0-2])$|^(3[0-1][0-9]{3}|[1-2][0-9]{4}|[1-9][0-9]{0,3}|32000)m$"
                      default: "1000m"
                    memory:
                      type: string
                      pattern: "^([1-9]|[1-5][0-9]|6[0-4])Gi$|^([1-9]|[1-9][0-9]{1,3}|[1-5][0-9]{4}|6[0-3][0-9]{3}|64000)Mi$"
                      default: "4Gi"
                limits:
                  type: object
                  properties:
                    cpu:
                      type: string
                      pattern: "^([1-9]|[12][0-9]|3[0-2])$|^(3[0-1][0-9]{3}|[1-2][0-9]{4}|[1-9][0-9]{0,3}|32000)m$"
                      default: "1000m"
                    memory:
                      type: string
                      pattern: "^([1-9]|[1-5][0-9]|6[0-4])Gi$|^([1-9]|[1-9][0-9]{1,3}|[1-5][0-9]{4}|6[0-3][0-9]{3}|64000)Mi$"
                      default: "4Gi"

    # Similar blocks for grafana, alertmanager, and kube-state-metrics...

  required:
    - operator
    - prometheus

  x-ui-order:
    - values
    - retention
    - node_selector
    - tolerations
    - operator
    - prometheus
    - grafana
    - alertmanager
    - kube-state-metrics

sample:
  $schema: https://facets-cloud.github.io/facets-schemas/schemas/prometheus/prometheus.schema.json
  flavor: k8s
  metadata: {}
  kind: prometheus
  version: "0.1"
  spec:
    retention: "100d"
    node_selector:
    tolerations:
    values: {}
    operator:
      enabled: true
      enable_crds: true
      size:
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
    prometheus:
      enabled: true
      size:
        volume: "100Gi"
        resources:
          requests:
            cpu: "1000m"
            memory: "4Gi"
          limits:
            cpu: "1000m"
            memory: "4Gi"
    grafana:
      enabled: true
      size:
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
    alertmanager:
      enabled: true
      volume: "10Gi"
      size:
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
    kube-state-metrics:
      enabled: true
      size:
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"