intent: k8s_resource
flavor: k8s
version: '0.1'
clouds:
  - aws
  - azure
  - gcp
  - kubernetes
spec:
  resource:
    type: object
    title: Resource
    description: This should contain the kubernetes YAML manifest. You can only pass one manifest per resource. If you need to create multiple resources, you need multiple json files.
    x-ui-yaml-editor: true
    x-ui-placeholder: Enter kubernetes manifest in YAML format
sample:
  $schema: >-
    https://facets-cloud.github.io/facets-schemas/schemas/k8s_resource/k8s_resource.schema.json
  kind: k8s_resource
  metadata: { }
  flavor: k8s
  version: 0.1
  disabled: true
  spec:
    resource:
      apiVersion: v1
      kind: Service
      metadata:
        name: k8s-resource
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-scheme: internal
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
      spec:
        selector:
          app: facetsapi
        type: ClusterIP
        ports:
          - port: 80
            name: http
            targetPort: 80

