{
 "title": "Application dashboard [New]",
 "description": "New Application level dashboard ",
 "time": { "from": "now-15d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\"},label_app)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\",label_app=~\"$service\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\",pod=~\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilisation ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",endpoint=\"https-metrics\",pod=~\"$pod\",image!=\"\", container!=\"POD\"}[2m])* 1000) ",
     "legendFormat": "avg-usage"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",endpoint=\"https-metrics\",pod=~\"$pod\",image!=\"\", container!=\"POD\"}[2m])* 1000) ",
     "legendFormat": "max-usage"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$pod\",container=~\"$container\",resource=\"cpu\",unit=\"core\"})*1000",
     "legendFormat": "limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$pod\",container=~\"$container\",resource=\"cpu\",unit=\"core\"})*1000",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Memory Utilisation ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$pod\",container=~\"$container\",resource=\"memory\",unit=\"byte\",container!=\"POD\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "max(container_memory_usage_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\",endpoint=\"https-metrics\",image!=\"\", container!=\"POD\"})",
     "legendFormat": "max-usage"
    },
    {
     "expr": "avg(container_memory_usage_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\",endpoint=\"https-metrics\",image!=\"\", container!=\"POD\"})",
     "legendFormat": "avg-usage"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$pod\",container=~\"$container\",resource=\"memory\",unit=\"byte\",container!=\"POD\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "VPA - CPU recommendations",
   "type": "stat",
   "description": "This gives the cpu recommendation and the cap limits for each services",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": " m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (kube_pod_container_resource_requests{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$pod\",container=~\"$container\",resource=\"cpu\",unit=\"core\"} * 1000 )",
     "legendFormat": "Current requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$pod\",container=~\"$container\",resource=\"cpu\",unit=\"core\"}*1000)",
     "legendFormat": "Current limits"
    },
    {
     "expr": "max(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{container=\"$service\",resource=\"cpu\", namespace=\"$namespace\"} * 1000)",
     "legendFormat": "Recommended requests"
    },
    {
     "expr": "max(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{container=\"$service\", resource=\"cpu\", namespace=\"$namespace\"} * 1000)",
     "legendFormat": "Recommended limits"
    }
   ]
  },
  {
   "title": "VPA - Memory Recommendations",
   "type": "stat",
   "description": "This gives the memory recommendation for the specific service",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$pod\",container=~\"$container\",resource=\"memory\",unit=\"byte\",container!=\"POD\"})",
     "legendFormat": "Current requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$pod\",container=~\"$container\",resource=\"memory\",unit=\"byte\",container!=\"POD\"})",
     "legendFormat": "Current limits"
    },
    {
     "expr": "max(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{container=\"$service\", resource=\"memory\", namespace=\"$namespace\"})",
     "legendFormat": "Recommended requests"
    },
    {
     "expr": "max(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{container=\"$service\", resource=\"memory\", namespace=\"$namespace\"})",
     "legendFormat": "Recommended limits"
    }
   ]
  },
  {
   "title": "CPU throttling",
   "type": "timeseries",
   "description": "container_cpu_cfs_throttled_seconds_total is the Total time duration the container has been throttled in seconds. container_cpu_cfs_throttled_periods_total is the Number of throttled period intervals",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod) ((container_cpu_cfs_throttled_periods_total{pod=~\"$service.*\", namespace=\"$namespace\"} / container_cpu_cfs_periods_total{pod=~\"$service.*\", namespace=\"$namespace\"}) * 100)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Termination ",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Scaling information ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 34 },
   "targets": [
    {
     "expr": "sum by (horizontalpodautoscaler)(kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\",horizontalpodautoscaler=~\"$service\"})",
     "legendFormat": "current-status-{{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "Total Container Restarts ",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"}[5m]))>0",
     "legendFormat": "Pod: {{pod}}, Container:  {{container}}"
    }
   ]
  },
  {
   "title": "Non Ready pods ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 44 },
   "targets": [
    {
     "expr": "group(kube_pod_status_ready{namespace=~\"$namespace\",pod=~\"$pod\",condition!=\"true\"}>0) by (pod,condition)",
     "legendFormat": "Pod: {{pod}} condition: {{condition}}"
    }
   ]
  },
  {
   "title": "Application Events",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "kube_event_exporter{involved_object_kind=~\"Endpoints|HorizontalPodAutoscaler|Pod|ReplicaSet|StatefulSet|Deployment\", involved_object_name=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}