{
 "title": "Ingress Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_ingress_path, namespace)"
    }
   },
   {
    "name": "services",
    "label": "Services",
    "query": {
     "query": "label_values(kube_ingress_path{namespace=~\"$namespace\"}, service_name)"
    }
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": {
     "query": "label_values(kube_ingress_path{namespace=~\"$namespace\",  service_name=~\"$services\"}, ingress)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(kube_ingress_path{namespace=~\"$namespace\",  service_name=~\"$services\"}, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Request Volume",
   "type": "gauge",
   "description": "The total number of requests per second for services",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{namespace=\"$namespace\", exported_service=~\"$services\"}[2m])), 0.001) or round(sum(irate(nginx_ingress_controller_requests{namespace=\"$namespace\", service=~\"$services\"}[2m])), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Percentile Response Times",
   "type": "timeseries",
   "description": "The percentile response times (P99, P90, P50) for each ingress for services",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le))",
     "legendFormat": "P50 {{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=\"$namespace\", ingress=~\"$ingress\"}[2m])) by (le))",
     "legendFormat": "P90 {{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=\"$namespace\", ingress=~\"$ingress\"}[2m])) by (le))",
     "legendFormat": "P99 {{ ingress }}"
    }
   ]
  },
  {
   "title": "Status Code Count",
   "type": "timeseries",
   "description": "The status code count for each ingress for the services",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(label_replace(increase(nginx_ingress_controller_requests{namespace=\"$namespace\",exported_service=~\"$services\"}[2m]), \"status_code\", \"${1}xx\", \"status\", \"(.)..\")) or sum(label_replace(increase(nginx_ingress_controller_requests{namespace=\"$namespace\",service=~\"$services\"}[2m]), \"status_code\", \"${1}xx\", \"status\", \"(.)..\")) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Services Health",
   "type": "table",
   "description": "The health of the services",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace=\"$namespace\", deployment=~\"$services\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "table",
   "description": "The SSL expiry for hosts in each ingress for the services",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "targets": [
    {
     "expr": "ssl_expiry{namespace=\"$namespace\", ingress=~\"$ingress\", domain=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}