{
 "title": "Kafka Cluster Metrics",
 "description": "Kafka Cluster Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "kafka_pods",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_activecontrollercount_value, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Genral Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Brokers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount_value{pod=\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ClusterPartitionCount",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_total_partitioncount_value{pod=~\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "OfflinePartitionsCount",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount_value{pod=~\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Topic Topics Per Broker",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globaltopiccount_value{pod=~\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Broker Message In / Minute",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_messagesinpersec_oneminuterate{pod=\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total Message In Per Broker",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_messagesinpersec_count{pod=\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPUUsed(%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_cpuload{pod=\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "MemoryUsed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_totalmemorysize{pod=\"$kafka_pods\"}",
     "legendFormat": "{{host}} - Total Memory Used "
    },
    {
     "expr": "java_lang_operatingsystem_freememorysize{pod=\"$kafka_pods\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "broker Bytes Sent by 1 Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_bytesinpersec_oneminuterate{pod=\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Broker Bytes out by 1 min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_bytesoutpersec_oneminuterate{pod=\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cluster Lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicafetchermanager_maxlag_value{pod=\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total Queue Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_controllerchannelmanager_totalqueuesize_value{pod=\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Partition Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UnderReplicatedPartitions by topic-partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_total_underreplicatedpartitions_value{pod=\"$kafka_pods\"}",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Produce Rquests Failed/Sec by [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_failedproducerequestspersec_oneminuterate{pod=\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Request Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Producer Request Bytes/1 Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_totalproducerequestspersec_oneminuterate{pod=\"$kafka_pods\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}