{
 "title": "Node Resource Allocation Summary",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster CPU Allocation Summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory Allocation Summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Resource Allocation",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"cpu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"cpu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"memory\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"memory\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}