{
 "title": "Kubernetes Windows Application Overview",
 "tags": [ "Facets" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "appName", "label": "Application Name", "query": "windowsop" }
  ]
 },
 "panels": [
  {
   "title": "Container CPU Cores Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(windows_container_cpu_usage_seconds_total[5m]) * on(container_id) group_left(namespace, pod, container) kube_pod_container_info{container=\"$appName\",pod=~\"$appName-[a-zA-Z0-9]*-[a-zA-Z0-9]*\"}) by (pod)",
     "legendFormat": "used-{{ pod }}"
    },
    {
     "expr": "container_spec_cpu_quota{image=\"\", pod=~\"$appName-[a-zA-Z0-9]*-[a-zA-Z0-9]*\"}/100000",
     "legendFormat": "limit-{{ pod }}"
    }
   ]
  },
  {
   "title": "Container GBytes of Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(windows_container_memory_usage_private_working_set_bytes * on(container_id) group_left(namespace, pod, container) kube_pod_container_info{pod=~\"$appName-[a-zA-Z0-9]*-[a-zA-Z0-9]*\", job=\"kube-state-metrics\", image!=\"\", container!=\"POD\"}/1073741824) by (pod)",
     "legendFormat": "used-{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$appName-[a-zA-Z0-9]*-[a-zA-Z0-9]*\", job=\"kube-state-metrics\", container!=\"POD\", resource=\"memory\"}/1073741824) by (pod)",
     "legendFormat": "limit-{{ pod }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage - % Used vs Limit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * max(windows_container_memory_usage_private_working_set_bytes * on(container_id) group_left(namespace, pod, container) kube_pod_container_info{pod=~\"$appName-[a-zA-Z0-9]*-[a-zA-Z0-9]*\", job=\"kube-state-metrics\", image!=\"\", container!=\"POD\"} / on (container, pod) kube_pod_container_resource_limits{pod=~\"$appName-[a-zA-Z0-9]*-[a-zA-Z0-9]*\", resource=\"memory\", job=\"kube-state-metrics\", container!=\"POD\"}) by (container)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Root volume usage (Gi)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{pod=~\"$appName-[a-zA-Z0-9]*-[a-zA-Z0-9]*\",device=\"/dev/nvme0n1p1\", container!=\"POD\"}/(1024*1024*1024)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"$appName-[a-zA-Z0-9]*-[a-zA-Z0-9]*\"} > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Not Ready",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase!=\"Running\",phase!=\"Succeeded\", pod=~\"$appName-[a-zA-Z0-9]*-[a-zA-Z0-9]*\"} > 0",
     "legendFormat": "{{ pod  }}-{{ phase }}"
    }
   ]
  },
  {
   "title": "Active Pods by Deployment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=~\"$appName\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  }
 ]
}