intent: kafka
flavor: k8s
version: "0.2"
description: Adds Kafka module of kubernetes flavor
clouds:
  - aws
  - azure
  - gcp
  - kubernetes
spec:
  title: Kafka Spec
  type: object
  properties:
    authenticated:
      type: boolean
      title: Authenticated
      description: Make this kafka password protected
    kafka_version:
      type: string
      title: Kafka Version
      description: Version of kafka e.g. 3.2.3
      enum:
        - 1.1.1
        - 2.8.1
    persistence_enabled:
      type: boolean
      title: Persistence Enabled
      description: Enable Persistence for this redis
    size:
      type: object
      title: Size
      description: The size details
      properties:
        zookeeper:
          type: object
          title: Zookeeper
          description: The zookeeper details
          properties:
            cpu:
              type: string
              title: CPU
              description: Number of CPU cores required
              pattern: "^([1-9]|[12][0-9]|3[0-2])$|^(3[0-1][0-9]{3}|[1-2][0-9]{4}|[1-9][0-9]{0,3}|32000)m$"
              x-ui-placeholder: "Enter CPU requests for your application"
              x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1 to 32 or 1m to 32000m"
            memory:
              type: string
              title: Memory
              description: Amount of memory required.
              pattern: "^(0\\.[1-9]|[1-9](\\.[0-9]+)?|[1-5][0-9](\\.[0-9]+)?|6[0-4])Gi$|^([1-9](\\.[0-9]+)?|[1-9][0-9]{1,3}(\\.[0-9]+)?|[1-5][0-9]{4}(\\.[0-9]+)?|6[0-3][0-9]{3}(\\.[0-9]+)?|64000)Mi$"
              x-ui-placeholder: "Enter Memory requests for your application"
              x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1Gi to 64Gi or 1Mi to 64000Mi"
            cpu_limit:
              type: string
              title: CPU Limit
              description: Set a maximum limit on CPU utilization.
              minLength: 1
              pattern: "^([1-9]|[12][0-9]|3[0-2])$|^(3[0-1][0-9]{3}|[1-2][0-9]{4}|[1-9][0-9]{0,3}|32000)m$"
              x-ui-placeholder: "e.g., '500m' or '1'"
              x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1 to 32 or 1m to 32000m"
            memory_limit:
              type: string
              title: Memory Limit
              description: Set a maximum limit on memory utilization.
              minLength: 1
              pattern: "^(0\\.[1-9]|[1-9](\\.[0-9]+)?|[1-5][0-9](\\.[0-9]+)?|6[0-4])Gi$|^([1-9](\\.[0-9]+)?|[1-9][0-9]{1,3}(\\.[0-9]+)?|[1-5][0-9]{4}(\\.[0-9]+)?|6[0-3][0-9]{3}(\\.[0-9]+)?|64000)Mi$"
              x-ui-placeholder: "e.g., '800Mi' or '1.5Gi'"
              x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1Gi to 64Gi or 1Mi to 64000Mi"            
            volume:
              type: string
              title: Volume
              description: Volume request in kubernetes persistent volumes
              pattern: "^[0-9]+[EiKMGTP]i?$"
              x-ui-placeholder: "Enter volume size"
              x-ui-error-message: "Value doesn't match '^[0-9]+[EiKMGTP]i?$' pattern"
            instance_count:
              type: integer
              title: Instance Count
              description: Number of zookeeper instances needs to be deployed
              minimum: 0
              maximum: 100
          required: ["cpu", "memory", "instance_count"]
        kafka:
          type: object
          title: Kafka
          description: The kafka details
          properties:
            cpu:
              type: string
              title: CPU
              description: Number of CPU cores required
              pattern: "^([1-9]|[12][0-9]|3[0-2])$|^(3[0-1][0-9]{3}|[1-2][0-9]{4}|[1-9][0-9]{0,3}|32000)m$"
              x-ui-placeholder: "e.g., '500m' or '1'"
              x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1 to 32 or 1m to 32000m"
            memory:
              type: string
              title: Memory
              description: Amount of memory required
              pattern: "^(0\\.[1-9]|[1-9](\\.[0-9]+)?|[1-5][0-9](\\.[0-9]+)?|6[0-4])Gi$|^([1-9](\\.[0-9]+)?|[1-9][0-9]{1,3}(\\.[0-9]+)?|[1-5][0-9]{4}(\\.[0-9]+)?|6[0-3][0-9]{3}(\\.[0-9]+)?|64000)Mi$"
              x-ui-placeholder: "e.g., '800Mi' or '1.5Gi'"
              x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1Gi to 64Gi or 1Mi to 64000Mi"
            cpu_limit:
              type: string
              title: CPU Limit
              description: Set a maximum limit on CPU utilization
              minLength: 1
              pattern: "^([1-9]|[12][0-9]|3[0-2])$|^(3[0-1][0-9]{3}|[1-2][0-9]{4}|[1-9][0-9]{0,3}|32000)m$"
              x-ui-placeholder: "e.g., '500m' or '1'"
              x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1 to 32 or 1m to 32000m"
            memory_limit:
              type: string
              title: Memory Limit
              description: Set a maximum limit on memory utilization
              minLength: 1
              pattern: "^(0\\.[1-9]|[1-9](\\.[0-9]+)?|[1-5][0-9](\\.[0-9]+)?|6[0-4])Gi$|^([1-9](\\.[0-9]+)?|[1-9][0-9]{1,3}(\\.[0-9]+)?|[1-5][0-9]{4}(\\.[0-9]+)?|6[0-3][0-9]{3}(\\.[0-9]+)?|64000)Mi$"
              x-ui-placeholder: "e.g., '800Mi' or '1.5Gi'"
              x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1Gi to 64Gi or 1Mi to 64000Mi"            
            volume:
              type: string
              title: Volume
              description: Volume request in kubernetes persistent volumes
              pattern: "^[0-9]+[EiKMGTP]i?$"
              x-ui-placeholder: "Enter volume size"
              x-ui-error-message: "Value doesn't match '^[0-9]+[EiKMGTP]i?$' pattern"
            instance_count:
              type: integer
              title: Instance Count
              description: Number of kafka instances needs to be deployed
              minimum: 0
              maximum: 100
          required: ["cpu", "memory", "instance_count"]
      required: ["zookeeper", "kafka"]
  required: ["authenticated", "kafka_version", "persistence_enabled", "size"]
sample:
  $schema: "https://facets-cloud.github.io/facets-schemas/schemas/kafka/kafka.schema.json"
  kind: kafka
  version: "0.2"
  flavor: k8s
  disabled: true
  metadata: {}
  spec:
    authenticated: true
    kafka_version: 2.8.1
    persistence_enabled: true
    size:
      kafka:
        cpu: "1"
        memory: 2Gi
        cpu_limit: "1"
        memory_limit: 2Gi
        instance_count: 1
        volume: 10Gi
      zookeeper:
        cpu: "1"
        memory: 1Gi
        cpu_limit: "1"
        memory_limit: 1Gi
        instance_count: 1
        volume: 10Gi
