intent: zookeeper
flavor: k8s
version: '0.1'
description: Adds zookeeper - k8s flavor
clouds:
- aws
- gcp
- azure
- kubernetes
sample:
  $schema: https://facets-cloud.github.io/facets-schemas/schemas/zookeeper/zookeeper.schema.json
  disabled: true
  flavor: k8s
  kind: zookeeper
  version: '0.1'
  metadata: {}
  spec:
    zookeeper_version: 3.8.1
    size:
      cpu: 500m
      memory: 500Mi
      volume: 8Gi
      replica_count: 1
