intent: cassandra
flavor: k8s
version: '0.1'
description: Adds cassandra - k8s flavor
clouds:
- aws
- gcp
- azure
- kubernetes
sample:
  $schema: https://facets-cloud.github.io/facets-schemas/schemas/cassandra/cassandra.schema.json
  flavor: k8s
  kind: cassandra
  metadata: {}
  spec:
    cassandra_version: 3.11.6
    size:
      cpu: '2'
      memory: 2Gi
      volume: 5Gi
      replica_count: 1
  disabled: true
