intent: rabbitmq
flavor: k8s
version: "0.1"
description: Adds rabbitmq k8s module
clouds:
  - aws
  - azure
  - gcp
  - kubernetes
metadata:
  title: Metadata of Mongo
  type: object
  properties:
    namespace:
      type: string
      title: Namespace
      description: Namespace in which Mongo should be deployed
spec:
  title: K8s rabbitmq
  type: object
  properties:
    rabbitmq_version:
      type: string
      title: RabbitMQ Version
      description: Version of RabbitMQ
      minLength: 1
      x-ui-typeable: true
      enum:
        - "3.10.7"
        - "3.10.19"
    size:
      type: object
      title: Size
      description: Datastore Sizing
      properties:
        cpu:
          type: string
          title: CPU
          description: Number of CPU cores required
          minLength: 1
          pattern: "^[0-9]+[m]?$"
          x-ui-compare:
            field: spec.size.cpu_limit
            comparator: "<="
            x-ui-error-message: "CPU cannot be more than CPU limit"
          x-ui-placeholder: "Enter CPU cores"
          x-ui-error-message: "Value doesn't match '^[0-9]+[m]?$' pattern"
        memory:
          type: string
          title: Memory
          description: Amount of required memory
          minLength: 1
          pattern: "^[0-9]+(\\.[0-9]+)?[EiKMGTP]i?$"
          x-ui-compare:
            field: spec.size.memory_limit
            comparator: "<="
            x-ui-error-message: "Memory cannot be more than memory limit"
          x-ui-placeholder: "Enter memory (Ex. 2Gi)"
          x-ui-error-message: "Value doesn't match '^[0-9]+(\\.[0-9]+)?[EiKMGTP]i?' pattern"
        cpu_limit:
          type: string
          title: CPU Limit
          description: CPU limit for the instance
          minLength: 1
          pattern: "^[0-9]+[m]?$"
          x-ui-compare:
            field: spec.size.cpu
            comparator: ">="
            x-ui-error-message: "CPU limit cannot be less than CPU"
          x-ui-placeholder: "Enter CPU limit"
          x-ui-error-message: "Value doesn't match '^[0-9]+[m]?$' pattern"
        memory_limit:
          type: string
          title: Memory Limit
          description: Memory limit for the instance
          minLength: 1
          pattern: "^[0-9]+(\\.[0-9]+)?[EiKMGTP]i?$"
          x-ui-compare:
            field: spec.size.memory
            comparator: ">="
            x-ui-error-message: "Memory limit cannot be less than memory"
          x-ui-placeholder: "Enter memory limit"
          x-ui-error-message: "Value doesn't match '^[0-9]+(\\.[0-9]+)?[EiKMGTP]i?' pattern"
        volume:
          type: string
          title: Volume
          description: Size of the volume
          pattern: "^[0-9]+[G]i?$"
          x-ui-placeholder: "Enter volume size"
          x-ui-error-message: "Value doesn't match '^[0-9]+[EiKMGTP]i?$' pattern"
        instance_count:
          type: integer
          title: Instance Count
          description: Number of instances to create
          minimum: 1
          maximum: 100
          x-ui-placeholder: "Enter instance count"
      required:
        - cpu
        - memory
        - volume
        - instance_count
  required:
    - size
    - rabbitmq_version
  x-ui-order:
    - rabbitmq_version
    - size
sample:
  $schema: "https://facets-cloud.github.io/facets-schemas/schemas/rabbitmq/rabbitmq.schema.json"
  version: "0.1"
  flavor: k8s
  kind: rabbitmq
  metadata: {}
  spec:
    rabbitmq_version: "3.10.19"
    size:
      cpu: 2
      memory: 2Gi
      volume: 8Gi
      instance_count: 1
  disabled: true
