{
 "title": "Service",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_pod_labels{label_resource_type=\"service\"}, label_app)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"default\", pod=~\"petclinic.*\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tempo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Rate",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(calls_total{service_name=~\"$deployment\", span_kind=\"SPAN_KIND_SERVER\", status_code=\"STATUS_CODE_ERROR\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(calls_total{span_kind=\"SPAN_KIND_SERVER\", k8s_namespace_name=\"$namespace\", k8s_deployment_name=\"$deployment\"}[2m]))\n",
       "legendFormat": "Hits"
      }
     ]
    },
    {
     "title": "OPS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(calls_total{span_kind=\"SPAN_KIND_SERVER\", k8s_namespace_name=\"$namespace\", k8s_deployment_name=\"$deployment\"}[2m]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests and Errors",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(calls_total{span_kind=\"SPAN_KIND_SERVER\", k8s_namespace_name=\"$namespace\", k8s_deployment_name=\"$deployment\", status_code!=\"STATUS_CODE_ERROR\"}[2m]))\n",
       "legendFormat": "Hits"
      },
      {
       "expr": "sum(increase(calls_total{span_kind=\"SPAN_KIND_SERVER\", k8s_namespace_name=\"$namespace\", k8s_deployment_name=\"$deployment\", status_code=\"STATUS_CODE_ERROR\"}[2m]))",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(duration_milliseconds_bucket[5m])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(duration_milliseconds_bucket[5m])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(duration_milliseconds_bucket[5m])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(duration_milliseconds_bucket[5m])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Top 7 Spans RPS",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(7,sum(rate(calls_total{service_name=~\"$deployment\", span_kind=\"SPAN_KIND_SERVER\"}[$__range])) by (span_name))",
       "legendFormat": "{{span_name}}"
      }
     ]
    },
    {
     "title": "Recent Traces",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "targets": [
      { "serviceName": "$deployment" }
     ]
    },
    {
     "title": "Slowest Traces",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(10, histogram_quantile(0.90, sum by (le, span_name) (rate(duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\"}[5m]))))",
       "legendFormat": "p99"
      },
      {
       "expr": "topk(10, histogram_quantile(0.99, sum by (le, span_name) (rate(duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\"}[5m]))))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Resource Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$deployment.*\",container!=\"\",resource=\"cpu\",unit=\"core\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Resource Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$deployment.*\",container!=\"\",resource=\"cpu\",unit=\"core\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$deployment.*\",container!=\"\",resource=\"memory\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$deployment.*\",container!=\"\",resource=\"memory\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization Analysis",
   "type": "timeseries",
   "description": "This dashboard displays the maximum and average CPU usage percentage for the application pods in the selected namespace. It compares the CPU usage rates against the requested CPU resources to highlight peak and overall CPU efficiency. This helps monitor resource utilization, detect over- or under-provisioning, and optimize CPU requests for better performance and cost management. ",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*avg(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$deployment.*\", container !=\"\"}[1m])) by (container) *1000/max(kube_pod_container_resource_requests{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$deployment.*\",container!=\"\",resource=\"cpu\",unit=\"core\"}*1000) by (container)",
     "legendFormat": "{{container}} - Average"
    },
    {
     "expr": "100*max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$deployment.*\", container !=\"\"}[1m])) by (container)*1000/max(kube_pod_container_resource_requests{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$deployment.*\",container!=\"\",resource=\"cpu\",unit=\"core\"}*1000) by (container)",
     "legendFormat": "{{container}} - Max"
    },
    {
     "expr": "100* sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$deployment.*\", container!=\"\"}[1m]))by (container)/sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"$deployment.*\", container!=\"\"}[1m])) by (container)",
     "legendFormat": "{{container}} - Throttlling "
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100* sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$deployment.*\", container!=\"\"}[$__range])) by (container)/sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"$deployment.*\", container!=\"\"}[$__range])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization Analysis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100* max(container_memory_usage_bytes{namespace=~\"$namespace\",pod=~\"$deployment.*\",container!=\"\"}) by (container)/max(kube_pod_container_resource_requests{namespace=~\"$namespace\",endpoint=\"http\",pod=~\"$deployment.*\",container!=\"\",resource=\"memory\"}) by (container)",
     "legendFormat": "{{container}} - Usage"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Health Status.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$deployment-.*\", container!=\"\", phase=~\"Failed|Pending|Unknown\"}) ",
     "legendFormat": "{{container}} - {{phase}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$deployment-.*\", container!=\"\"}>0) by (phase, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$deployment-.*\", container!=\"\"}>0) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Status.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$deployment-.*\", container!=\"\", phase=~\"Running\"})",
     "legendFormat": "{{container}} - {{phase}}"
    }
   ]
  },
  {
   "title": "Loki Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", app=~\"$deployment\"} | json | container=~\"$container\"[$__interval])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "{app=~\"$deployment\"} |= `` | json | container=~\"$container\" ",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  }
 ]
}