{
 "title": "Loki",
 "tags": [
  "Facets",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Non Ready Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled{daemonset=~\".*promtail\"} - kube_daemonset_status_number_ready{daemonset=~\".*promtail\"}",
     "legendFormat": "{{daemonset}}"
    },
    {
     "expr": "kube_deployment_status_replicas{deployment=~\".*distributor\"} - kube_deployment_status_replicas_available{deployment=~\".*distributor\"}",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_statefulset_status_replicas{statefulset=~\".*ingester\"} - kube_statefulset_status_replicas_ready{statefulset=~\".*ingester\"}",
     "legendFormat": "{{statefulset}}"
    },
    {
     "expr": "kube_deployment_status_replicas{deployment=~\".*query-frontend\"} - kube_deployment_status_replicas_available{deployment=~\".*query-frontend\"}",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_statefulset_status_replicas{statefulset=~\".*querier\"} - kube_statefulset_status_replicas_ready{statefulset=~\".*querier\"}",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{container=~\"compactor|query-frontend|querier|ingester|distributor|promtail\"}[5m]) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OOM Killed Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\", container=~\"compactor|query-frontend|querier|ingester|distributor|promtail\"}) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{container=~\"promtail|distributor|ingester|querier|query-frontend\"}[5m])) by (container, pod, namespace) / sum(increase(container_cpu_cfs_periods_total{container=~\"promtail|distributor|ingester|querier|query-frontend\"}[5m])) by (container, pod, namespace) * 100 > 70",
     "legendFormat": "{{pod}}"
    },
    {}
   ]
  },
  {
   "title": "Memory Throttling",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\"promtail|distributor|ingester|querier|query-frontend\"}) by (pod, container_name) / sum(container_spec_memory_limit_bytes{container=~\"promtail|distributor|ingester|querier|query-frontend\"}) by (pod, container_name) * 100 > 70",
     "legendFormat": "{{pod}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Promtail Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(promtail_request_duration_seconds_bucket[1m])) by (le, job))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(promtail_request_duration_seconds_bucket[1m])) by (le, job))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(promtail_request_duration_seconds_sum[1m])) by (job) / sum(rate(promtail_request_duration_seconds_count[1m])) by (job)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Log Entries Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(promtail_dropped_entries_total[1m]) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}