spec:
  title: K8s flavor of service
  type: object
  x-ui-override: true
  properties:
    type:
      type: string
      title: Service Type
      description: Type- Application, Statefulset, Cronjob, Job
      enum:
        - application
    restart_policy:
      type: string
      title: Restart Policy
      description: Restart Policy- Always, OnFailure, Never
      enum:
        - Always
        - OnFailure
        - Never
    enable_host_anti_affinity:
      type: boolean
      title: Enable Host Anti-Affinity
      description: Enable/disable host anti-affinity
    runtime:
      type: object
      title: Runtime
      x-ui-override: true
      description: Runtime configuration
      properties:
        health_checks:
          type: object
          title: Health Checks
          description: Health check key value pairs
          x-ui-toggle: true
          properties:
            readiness_check_type:
              type: string
              title: Readiness Check Type
              default: None
              enum:
                - None
                - PortCheck
                - HttpCheck
                - ExecCheck
            readiness_start_up_time:
              type: integer
              title: Readiness Start-Up Time
              default: 30
              x-ui-visible-if:
                field: spec.runtime.health_checks.readiness_check_type
                values: [ "PortCheck", "HttpCheck", "ExecCheck" ]
              description: Wait time for readiness check (in sec)
            readiness_timeout:
              type: integer
              title: Readiness Timeout
              default: 5
              x-ui-visible-if:
                field: spec.runtime.health_checks.readiness_check_type
                values: [ "PortCheck", "HttpCheck", "ExecCheck" ]
              description: Max time for readiness (in sec)
            readiness_period:
              type: integer
              title: Readiness Check Interval
              default: 30
              x-ui-visible-if:
                field: spec.runtime.health_checks.readiness_check_type
                values: [ "PortCheck", "HttpCheck", "ExecCheck" ]
              description: Repeated interval for health-check (in sec)
            readiness_port:
              type: string
              title: Readiness Port
              x-ui-visible-if:
                field: spec.runtime.health_checks.readiness_check_type
                values: [ "PortCheck", "HttpCheck" ]
              description: Port for Health Checks
              x-ui-dynamic-enum: spec.runtime.ports.*.port           
            readiness_url:
              type: string
              title: Readiness URL
              x-ui-visible-if:
                field: spec.runtime.health_checks.readiness_check_type
                values: [ "HttpCheck" ]
              description: URL for readiness
            readiness_exec_command:
              type: array
              title: Readiness Exec Command
              x-ui-visible-if:
                field: spec.runtime.health_checks.readiness_check_type
                values: [ "ExecCheck" ]
              description: Commands for readiness check

            liveness_check_type:
              type: string
              title: Liveness Check Type
              default: None
              enum:
                - None
                - PortCheck
                - HttpCheck
                - ExecCheck
            liveness_start_up_time:
              type: integer
              default: 30
              title: Liveness Start-Up Time
              x-ui-visible-if:
                field: spec.runtime.health_checks.liveness_check_type
                values: [ "PortCheck", "HttpCheck", "ExecCheck" ]
              description: Wait time for liveness (in sec)
            liveness_timeout:
              type: integer
              default: 5
              title: Liveness Timeout
              x-ui-visible-if:
                field: "spec.runtime.health_checks.liveness_check_type"
                values: [ "PortCheck", "HttpCheck", "ExecCheck" ]
              description: Max time for liveness (in sec)         
            liveness_period:
              type: integer
              title: Liveness Check Interval
              default: 30
              x-ui-visible-if:
                field: "spec.runtime.health_checks.liveness_check_type"
                values: [ "PortCheck", "HttpCheck", "ExecCheck" ]
              description: Interval for Liveness (in sec) 
            liveness_port:
              type: string
              title: Liveness Port
              x-ui-visible-if:
                field: "spec.runtime.health_checks.liveness_check_type"
                values: [ "PortCheck", "HttpCheck" ]
              description: Port for Health Checks
              x-ui-dynamic-enum: spec.runtime.ports.*.port            
            liveness_url:
              type: string
              title: Liveness URL
              x-ui-visible-if:
                field: "spec.runtime.health_checks.liveness_check_type"
                values: [ "HttpCheck" ]
              description: URL for liveness
            liveness_exec_command:
              type: array
              title: Liveness Exec Command
              x-ui-visible-if:
                field: "spec.runtime.health_checks.liveness_check_type"
                values: [ "ExecCheck" ]
              description: Commands for liveness            
        autoscaling:
          type: object
          title: Autoscaling
          description: Autoscaling configuration
          x-ui-toggle: true
          properties:
            min:
              type: integer
              title: Min
              default: 1
              minimum: 1
              description: Min replicas
            max:
              type: integer
              title: Max
              default: 1
              minimum: 1
              description: Max replicas
            scaling_on:
              type: string
              title: Scale based on
              default: None
              enum:
                - None
                - CPU
                - RAM
                - RPS
                - PPS
            cpu_threshold:
              type: string
              title: CPU Threshold
              description: Max CPU threshold
              x-ui-visible-if:
                field: "spec.runtime.autoscaling.scaling_on"
                values: [ "CPU" ]
            ram_threshold:
              type: string
              title: RAM Threshold
              description: Max RAM threshold
              x-ui-visible-if:
                field: "spec.runtime.autoscaling.scaling_on"
                values: [ "RAM" ]
            packets_per_second:
              type: string
              title: Packets Per Second
              description: Max packets per second
              x-ui-visible-if:
                field: "spec.runtime.autoscaling.scaling_on"
                values: [ "PPS" ]
            requests_per_second:
              type: object
              title: Requests Per Second
              description: Requests per second RPS
              x-ui-visible-if:
                field: "spec.runtime.autoscaling.scaling_on"
                values: [ "RPS" ]
              properties:
                threshold:
                  type: string
                  title: Threshold
                  description: RPS threshold
                ingress_name:
                  type: string
                  title: Ingress Name
                  description: Ingress name for autoscaling
              required:
                - threshold
                - ingress_name
        size:
          type: object
          title: Size
          description: Size configuration
          x-ui-override: true
          properties:
            cpu:
              type: string
              title: CPU
              description: CPU size
              pattern: '^[0-9]+[m]?$'
              x-ui-override: true
            memory:
              type: string
              title: Memory
              description: Memory size
              pattern: '^[0-9]+(\.[0-9]+)?[EiKMGTP]i?'
              x-ui-override: true
            cpu_limit:
              type: string
              title: CPU Limit
              description: CPU limit size
              pattern: '^[0-9]+[m]?$'
              x-ui-override: true
            memory_limit:
              type: string
              title: Memory Limit
              description: Memory limit size
              pattern: '^[0-9]+(\.[0-9]+)?[EiKMGTP]i?'
              x-ui-override: true
          required:
            - cpu
            - memory
        ports:
          type: object
          title: Ports
          description: Port mappings
          patternProperties:
            type: object
            title: Port Name
            description: Port details
            keyPattern: '^[0-9]+[m]?$'
            properties:
              port:
                type: string
                title: Port
                description: Pod port
              service_port:
                type: string
                title: Service Port
                description: Service port
              protocol:
                type: string
                title: Protocol
                description: TCP or UDP
                enum:
                  - tcp
                  - udp
            required:
              - protocol
              - port
        metrics:
          type: object
          title: Metrics
          x-ui-toggle: true
          description: Metrics port mappings
          patternProperties:
            type: object
            title: Metrics Name
            description: Metrics details
            keyPattern: '^[a-zA-Z0-9_.-]*$'
            properties:
              path:
                type: string
                title: Path
                description: Metrics path
              port_name:
                type: string
                title: Port Name
                description: Port name for metrics
                x-ui-dynamic-enum: spec.runtime.ports.*
            required:
              - path
              - port_name
        volumes:
          type: object
          title: Volumes
          x-ui-toggle: true
          description: Volume configurations
          properties:
            config_maps:
              type: object
              title: Config Maps
              description: Config map mounts
              patternProperties:
                type: object
                title: Config Map Name
                keyPattern: '^[a-zA-Z0-9_.-]*$'
                properties:
                  name:
                    type: string
                    title: Name
                    description: Config map name
                  mount_path:
                    type: string
                    title: Mount Path
                    description: Mount path for config maps
            secrets:
              type: object
              title: Secrets
              description: Secret mounts
              patternProperties:
                type: object
                title: Secret name
                keyPattern: '^[a-zA-Z0-9_.-]*$'
                properties:
                  name:
                    type: string
                    title: Name
                    description: Secret name
                  mount_path:
                    type: string
                    title: Mount Path
                    description: Mount path for secrets
            pvc:
              type: object
              title: PVC
              description: PVC mounts
              patternProperties:
                type: object
                title: PVC Name
                keyPattern: '^[a-zA-Z0-9_.-]*$'
                properties:
                  claim_name:
                    type: string
                    title: Claim Name
                    description: PVC name
                  mount_path:
                    type: string
                    title: Mount Path
                    description: Mount path for PVC
            host_path:
              type: object
              title: Host Path
              description: Host path mounts
              patternProperties:
                type: object
                title: Host Path Name
                keyPattern: '^[a-zA-Z0-9_.-]*$'
                properties:
                  mount_path:
                    type: string
                    title: Mount Path
                    description: Mount path for host path
      required:
        - ports
        - size
        - health_checks
      x-ui-order:
        - ports
        - metrics
        - size
        - health_checks
        - autoscaling
        - volumes
    release:
      type: object
      title: Release
      description: Release configuration
      properties: { }
  required:
    - type
    - restart_policy
    - enable_host_anti_affinity
    - runtime
  x-ui-order:
    - type
    - restart_policy
    - enable_host_anti_affinity
    - runtime
