intent: service
flavor: k8s
version: '0.1'
clouds:
- aws
- azure
- gcp
- kubernetes
spec:
  title: K8s flavor of service
  type: object
  properties:
    type:
      type: string
      title: Service Type
      description: Just application for now
      x-ui-override-disable: true
      enum:
        - application
    restart_policy:
      type: string
      title: Restart Policy
      description: Restart Policy- Always, OnFailure, Never
      x-ui-override-disable: true
      enum:
        - Always
        - OnFailure
        - Never
    enable_host_anti_affinity:
      type: boolean
      title: Enable Host Anti-Affinity
      description: Enable/disable host anti-affinity
    runtime:
      type: object
      title: Runtime
      description: Runtime configuration
      properties:
        health_checks:
          type: object
          title: Health Checks
          description: Health check key value pairs
          x-ui-override-disable: true
          x-ui-toggle: true
          properties:
            readiness_check_type:
              type: string
              title: Readiness Check Type
              default: None
              enum:
                - None
                - PortCheck
                - HttpCheck
                - ExecCheck
            readiness_start_up_time:
              type: integer
              title: Readiness Start-Up Time
              default: 30
              x-ui-visible-if:
                field: spec.runtime.health_checks.readiness_check_type
                values: [ "PortCheck", "HttpCheck", "ExecCheck" ]
              description: Wait time for readiness check (in sec)
            readiness_timeout:
              type: integer
              title: Readiness Timeout
              default: 5
              x-ui-visible-if:
                field: spec.runtime.health_checks.readiness_check_type
                values: [ "PortCheck", "HttpCheck", "ExecCheck" ]
              description: Max time for readiness (in sec)
            readiness_period:
              type: integer
              title: Readiness Check Interval
              default: 30
              x-ui-visible-if:
                field: spec.runtime.health_checks.readiness_check_type
                values: [ "PortCheck", "HttpCheck", "ExecCheck" ]
              description: Repeated interval for health-check (in sec)
            readiness_port:
              type: string
              title: Readiness Port
              x-ui-visible-if:
                field: spec.runtime.health_checks.readiness_check_type
                values: [ "PortCheck", "HttpCheck" ]
              description: Port for Health Checks
              x-ui-dynamic-enum: spec.runtime.ports.*.port
              x-ui-disable-tooltip: "No Ports Added"
            readiness_url:
              type: string
              title: Readiness URL
              x-ui-visible-if:
                field: spec.runtime.health_checks.readiness_check_type
                values: [ "HttpCheck" ]
              description: URL for readiness
            readiness_exec_command:
              type: array
              title: Readiness Exec Command
              x-ui-visible-if:
                field: spec.runtime.health_checks.readiness_check_type
                values: [ "ExecCheck" ]
              description: Commands for readiness check

            liveness_check_type:
              type: string
              title: Liveness Check Type
              default: None
              enum:
                - None
                - PortCheck
                - HttpCheck
                - ExecCheck
            liveness_start_up_time:
              type: integer
              default: 30
              title: Liveness Start-Up Time
              x-ui-visible-if:
                field: spec.runtime.health_checks.liveness_check_type
                values: [ "PortCheck", "HttpCheck", "ExecCheck" ]
              description: Wait time for liveness (in sec)
            liveness_timeout:
              type: integer
              default: 5
              title: Liveness Timeout
              x-ui-visible-if:
                field: "spec.runtime.health_checks.liveness_check_type"
                values: [ "PortCheck", "HttpCheck", "ExecCheck" ]
              description: Max time for liveness (in sec)
            liveness_period:
              type: integer
              title: Liveness Check Interval
              default: 30
              x-ui-visible-if:
                field: "spec.runtime.health_checks.liveness_check_type"
                values: [ "PortCheck", "HttpCheck", "ExecCheck" ]
              description: Interval for Liveness (in sec)
            liveness_port:
              type: string
              title: Liveness Port
              x-ui-visible-if:
                field: "spec.runtime.health_checks.liveness_check_type"
                values: [ "PortCheck", "HttpCheck" ]
              description: Port for Health Checks
              x-ui-dynamic-enum: spec.runtime.ports.*.port
              x-ui-disable-tooltip: "No Ports Added"
            liveness_url:
              type: string
              title: Liveness URL
              x-ui-visible-if:
                field: "spec.runtime.health_checks.liveness_check_type"
                values: [ "HttpCheck" ]
              description: URL for liveness
            liveness_exec_command:
              type: array
              title: Liveness Exec Command
              x-ui-visible-if:
                field: "spec.runtime.health_checks.liveness_check_type"
                values: [ "ExecCheck" ]
              description: Commands for liveness
        autoscaling:
          type: object
          title: Autoscaling
          description: Autoscaling configuration
          x-ui-toggle: true
          properties:
            min:
              type: integer
              title: Min
              default: 1
              minimum: 1
              description: Min replicas
            max:
              type: integer
              title: Max
              default: 1
              minimum: 1
              description: Max replicas
            scaling_on:
              type: string
              title: Scale based on
              default: None
              enum:
                - None
                - CPU
                - RAM
            cpu_threshold:
              type: string
              title: CPU Threshold
              description: Max CPU threshold
              x-ui-visible-if:
                field: "spec.runtime.autoscaling.scaling_on"
                values: [ "CPU" ]
            ram_threshold:
              type: string
              title: RAM Threshold
              description: Max RAM threshold
              x-ui-visible-if:
                field: "spec.runtime.autoscaling.scaling_on"
                values: [ "RAM" ]
        size:
          type: object
          title: Size
          description: Size configuration
          properties:
            cpu:
              type: string
              title: CPU
              description: CPU size
              pattern: '^[0-9]+[m]?$'
            memory:
              type: string
              title: Memory
              description: Memory size
              pattern: '^[0-9]+(\.[0-9]+)?[EiKMGTP]i?'
            cpu_limit:
              type: string
              title: CPU Limit
              description: CPU limit size
              pattern: '^[0-9]+[m]?$'
            memory_limit:
              type: string
              title: Memory Limit
              description: Memory limit size
              pattern: '^[0-9]+(\.[0-9]+)?[EiKMGTP]i?'
          required:
            - cpu
            - memory
        ports:
          type: object
          title: Ports
          x-ui-override-disable: true
          description: Port mappings
          patternProperties:
            type: object
            title: Port Name
            description: Port details
            keyPattern: '^[0-9]+[m]?$'
            properties:
              port:
                type: string
                title: Port
                description: Pod port
              service_port:
                type: string
                title: Service Port
                description: Service port
              protocol:
                type: string
                title: Protocol
                description: TCP or UDP
                enum:
                  - tcp
                  - udp
            required:
              - protocol
              - port
        metrics:
          type: object
          title: Metrics
          x-ui-override-disable: true
          x-ui-toggle: true
          description: Metrics port mappings
          patternProperties:
            type: object
            title: Metrics Name
            description: Metrics details
            keyPattern: '^[a-zA-Z0-9_.-]*$'
            properties:
              path:
                type: string
                title: Path
                description: Metrics path
              port_name:
                type: string
                title: Port Name
                description: Port name for metrics
                x-ui-dynamic-enum: spec.runtime.ports.*
                x-ui-disable-tooltip: "No Ports Available"
            required:
              - path
              - port_name
          x-ui-skip: true
        volumes:
          type: object
          title: Volumes
          x-ui-override-disable: true
          x-ui-toggle: true
          description: Volume configurations
          properties:
            config_maps:
              type: object
              title: Config Maps
              description: Config map mounts
              patternProperties:
                type: object
                title: Config Map Name
                keyPattern: '^[a-zA-Z0-9_.-]*$'
                properties:
                  name:
                    type: string
                    title: Name
                    description: Config map name
                  mount_path:
                    type: string
                    title: Mount Path
                    description: Mount path for config maps
            secrets:
              type: object
              title: Secrets
              description: Secret mounts
              patternProperties:
                type: object
                title: Secret name
                keyPattern: '^[a-zA-Z0-9_.-]*$'
                properties:
                  name:
                    type: string
                    title: Name
                    description: Secret name
                  mount_path:
                    type: string
                    title: Mount Path
                    description: Mount path for secrets
            pvc:
              type: object
              title: PVC
              description: PVC mounts
              patternProperties:
                type: object
                title: PVC Name
                keyPattern: '^[a-zA-Z0-9_.-]*$'
                properties:
                  claim_name:
                    type: string
                    title: Claim Name
                    description: PVC name
                  mount_path:
                    type: string
                    title: Mount Path
                    description: Mount path for PVC
            host_path:
              type: object
              title: Host Path
              description: Host path mounts
              patternProperties:
                type: object
                title: Host Path Name
                keyPattern: '^[a-zA-Z0-9_.-]*$'
                properties:
                  mount_path:
                    type: string
                    title: Mount Path
                    description: Mount path for host path
      required:
        - ports
        - size
        - health_checks
      x-ui-order:
        - ports
        - metrics
        - size
        - health_checks
        - autoscaling
        - volumes
    release:
      title: Release
      description: Map of all release keys
      type: object
      properties:
        image:
          type: string
          title: Image
          description: The docker image of the application that you want to run
          x-ui-skip: true
        build:
          type: object
          title: Build
          description: These contains the build objects required for running the containers
          properties:
            artifactory:
              type: string
              title: Artifactory
              description: Parent artifactory name
            name:
              type: string
              title: Name
              description: Name of the artifactory
            pull_policy:
              type: string
              title: Pull Policy
              description: ImagePullPolicy
              enum:
                - IfNotPresent
                - Always
                - Never
          required: [ "artifactory", "name" ]
          x-ui-skip: true
        strategy:
          type: object
          title: Strategy
          description: The type of upgrade strategy to be followed by this service
          properties:
            type:
              type: string
              title: Type
              description: "Your kubernetes rollout type eg: RollingUpdate or Recreate"
              enum:
                - RollingUpdate
                - Recreate
            max_available:
              type: string
              title: Max Available
              description: If type RollingUpdate, this is the max number of pods that can be created from the default replicas
            max_unavailable:
              type: string
              title: Max Unavailable
              description: If type RollingUpdate, this is the max number of pods that can be unavailable from the default replicas
        disruption_policy:
          type: object
          title: Disruption Policy
          description: The disruption policy for the service
          properties:
            min_available:
              type: string
              title: Min Available
              description: This is the min number of pods should be available in case of failures
            max_unavailable:
              type: string
              title: Max Unavailable
              description: This is the max number of pods that can be unavailable during a failure.
  required:
    - type
    - restart_policy
    - enable_host_anti_affinity
    - runtime
  x-ui-order:
    - type
    - restart_policy
    - enable_host_anti_affinity
    - runtime
    - release
sample:
  $schema: >-
    https://facets-cloud.github.io/facets-schemas/schemas/service/service.schema.json
  flavor: k8s
  metadata:
    labels:
      deliveryType: MANUAL
  kind: service
  disabled: true
  version: '0.1'
  spec:
    enable_host_anti_affinity: false
    type: application
    restart_policy: Always
    release:
      strategy:
        type: RollingUpdate
      build:
        artifactory: default
        name: replace-with-app-name
    runtime:
      autoscaling:
        scaling_on: CPU
        min: '1'
        max: '1'
        cpu_threshold: '50'
      ports:
        http:
          port: '8080'
          service_port: '8080'
          protocol: tcp
      size:
        cpu: 300m
        memory: 1Gi
        cpu_limit: 1000m
        memory_limit: 5Gi
      health_checks:
        readiness_check_type: PortCheck
        readiness_timeout: '10'
        readiness_period: '30'
        readiness_port: '8080'
        readiness_start_up_time: '15'
        liveness_check_type: PortCheck
        liveness_timeout: '10'
        liveness_period: '30'
        liveness_port: '8080'
        liveness_start_up_time: '15'
      volumes: { }
    env:
      LOG_LEVEL: INFO

