intent: elk
flavor: k8s
version: "0.1"
description: Adds ELK module of Kubernetes flavor
clouds:
  - aws
  - azure
  - gcp
  - kubernetes
spec:
  title: K8s
  type: object
  properties:
    elasticsearch:
      type: object
      title: Elasticsearch
      description: Elasticsearch configuration.
      properties:
        volume:
          type: string
          title: Volume
          description: Size of the Elasticsearch volume.
          minLength: 1
          pattern: "^[0-9]+(\\.[0-9]+)?[G]i?$"
          x-ui-placeholder: "e.g., '30Gi'"
          x-ui-error-message: "Volume must be specified in the correct format (e.g., '30Gi')."
        cpu:
          type: string
          title: CPU
          description: Number of CPU cores required.
          minLength: 1
          pattern: "^([1-9]|[12][0-9]|3[0-2])$|^(3[0-1][0-9]{3}|[1-2][0-9]{4}|[1-9][0-9]{0,3}|32000)m$"
          x-ui-placeholder: "e.g., '2' or '2000m'"
          x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1 to 32 or 1m to 32000m"
        memory:
          type: string
          title: Memory
          description: Amount of memory required.
          minLength: 1
          pattern: "^([1-9]|[1-5][0-9]|6[0-4])Gi$|^([1-9]|[1-9][0-9]{1,3}|[1-5][0-9]{4}|6[0-3][0-9]{3}|64000)Mi$"
          x-ui-placeholder: "e.g., '4Gi' or '4096Mi'"
          x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1Gi to 64Gi or 1Mi to 64000Mi"
        instance_count:
          type: integer
          title: Instance Count
          description: Number of Elasticsearch instances to create.
          minimum: 1
          maximum: 10
          x-ui-placeholder: "e.g., 1 or 3"
          x-ui-error-message: "Instance count must be between 1 and 10."
      required:
        - volume
        - cpu
        - memory
        - instance_count
    kibana:
      type: object
      title: Kibana
      description: Kibana configuration.
      properties:
        cpu:
          type: string
          title: CPU
          description: Number of CPU cores required.
          minLength: 1
          pattern: "^([1-9]|[12][0-9]|3[0-2])$|^(3[0-1][0-9]{3}|[1-2][0-9]{4}|[1-9][0-9]{0,3}|32000)m$"
          x-ui-placeholder: "e.g., '2' or '2000m'"
          x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1 to 32 or 1m to 32000m"
        memory:
          type: string
          title: Memory
          description: Amount of memory required.
          minLength: 1
          pattern: "^([1-9]|[1-5][0-9]|6[0-4])Gi$|^([1-9]|[1-9][0-9]{1,3}|[1-5][0-9]{4}|6[0-3][0-9]{3}|64000)Mi$"
          x-ui-placeholder: "e.g., '4Gi' or '4096Mi'"
          x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1Gi to 64Gi or 1Mi to 64000Mi"
        instance_count:
          type: integer
          title: Instance Count
          description: Number of Kibana instances to create.
          minimum: 1
          maximum: 10
          x-ui-placeholder: "e.g., 1 or 3"
          x-ui-error-message: "Instance count must be between 1 and 10."
      required:
        - cpu
        - memory
        - instance_count
    logstash:
      type: object
      title: Logstash
      description: Logstash configuration.
      properties:
        volume:
          type: string
          title: Volume
          description: Size of the Logstash volume.
          minLength: 1
          pattern: "^[0-9]+(\\.[0-9]+)?[G]i?$"
          x-ui-placeholder: "e.g., '10Gi'"
          x-ui-error-message: "Volume must be specified in the correct format (e.g., '10Gi')."
        cpu:
          type: string
          title: CPU
          description: Number of CPU cores required.
          minLength: 1
          pattern: "^([1-9]|[12][0-9]|3[0-2])$|^(3[0-1][0-9]{3}|[1-2][0-9]{4}|[1-9][0-9]{0,3}|32000)m$"
          x-ui-placeholder: "e.g., '2' or '2000m'"
          x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1 to 32 or 1m to 32000m"
        memory:
          type: string
          title: Memory
          description: Amount of memory required.
          minLength: 1
          pattern: "^([1-9]|[1-5][0-9]|6[0-4])Gi$|^([1-9]|[1-9][0-9]{1,3}|[1-5][0-9]{4}|6[0-3][0-9]{3}|64000)Mi$"
          x-ui-placeholder: "e.g., '4Gi' or '4096Mi'"
          x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1Gi to 64Gi or 1Mi to 64000Mi"
      required:
        - volume
        - cpu
        - memory
    filebeat:
      type: object
      title: Filebeat
      description: Filebeat configuration.
      properties:
        cpu:
          type: string
          title: CPU
          description: Number of CPU cores required.
          minLength: 1
          pattern: "^([1-9]|[12][0-9]|3[0-2])$|^(3[0-1][0-9]{3}|[1-2][0-9]{4}|[1-9][0-9]{0,3}|32000)m$"
          x-ui-placeholder: "e.g., '200m' or '2'"
          x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1 to 32 or 1m to 32000m"
        memory:
          type: string
          title: Memory
          description: Amount of memory required.
          minLength: 1
          pattern: "^([1-9]|[1-5][0-9]|6[0-4])Gi$|^([1-9]|[1-9][0-9]{1,3}|[1-5][0-9]{4}|6[0-3][0-9]{3}|64000)Mi$"
          x-ui-placeholder: "e.g., '400Mi' or '4Gi'"
          x-ui-error-message: "Value doesn't match pattern, it should be number ranging from 1Gi to 64Gi or 1Mi to 64000Mi"
      required:
        - cpu
        - memory
  required:
    - elasticsearch
    - kibana
    - logstash
    - filebeat
  x-ui-order:
    - elasticsearch
    - kibana
    - logstash
    - filebeat
sample:
  $schema: >-
    https://facets-cloud.github.io/facets-schemas/schemas/elk/elk.schema.json
  flavor: k8s
  metadata: {}
  kind: elk
  disabled: false
  version: "0.1"
  spec:
    elasticsearch:
      volume: "30Gi"
      cpu: "2"
      memory: "4Gi"
      instance_count: 1
    kibana:
      cpu: "2"
      memory: "4Gi"
      instance_count: 1
    logstash:
      volume: "10Gi"
      cpu: "2"
      memory: "4Gi"
    filebeat:
      cpu: "200m"
      memory: "400Mi"