name: Publish Module Zips

on:
  push:
    branches:
      - master

concurrency:
  group: publish-module-zips

jobs:
  publish:
    runs-on: iac-arc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Module Zips
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: python .github/workflows/zip_modules.py  # Run the script from workflows folder
